# Generated by Django 5.1.1 on 2024-10-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_initial'),
        ('inscripciones', '0001_initial'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inasistencias', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial_1', models.FloatField()),
                ('parcial_2', models.FloatField()),
                ('nota_final', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.curso')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.estado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.docente')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.recursos')),
            ],
        ),
    ]
