# Generated by Django 5.1.1 on 2024-11-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_initial'),
        ('alumno', '0002_initial'),
        ('inscripciones', '0001_initial'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inasistencias', models.IntegerField()),
                ('año_lectivo', models.IntegerField(default=2024)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.materia')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre_1', models.FloatField(blank=True, default=0, null=True)),
                ('trimestre_2', models.FloatField(blank=True, default=0, null=True)),
                ('trimestre_3', models.FloatField(blank=True, default=0, null=True)),
                ('nota_final', models.FloatField(blank=True, default=0, null=True)),
                ('año_lectivo', models.IntegerField(default=2024)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.curso')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.estado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(default='Sin observaciones.', max_length=50)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.docente')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.recursos')),
            ],
        ),
    ]
