# Generated by Django 5.1.1 on 2024-10-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.materia'),
        ),
        migrations.AddField(
            model_name='docente',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.genero'),
        ),
        migrations.AddField(
            model_name='docente',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.nacionalidad'),
        ),
        migrations.AddField(
            model_name='personaladmin',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.genero'),
        ),
        migrations.AddField(
            model_name='personaladmin',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.nacionalidad'),
        ),
        migrations.AddField(
            model_name='personaladmin',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.turno'),
        ),
    ]
