# Generated by Django 5.1.1 on 2024-11-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NombreRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.nombrerecurso')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.tiporecurso')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.ubicacion')),
            ],
        ),
    ]
