# Generated by Django 5.1.1 on 2024-11-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_initial'),
        ('alumno', '0001_initial'),
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.genero'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.nacionalidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='padretutor_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscripciones.padretutor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.turno'),
        ),
    ]
